CREATE DATABASE COMPANY DEFAULT CHARACTER SET UTF8 DEFAULT COLLATE UTF8_GENERAL_CI;
USE COMPANY;
CREATE TABLE DEPARTMENT(
DEPTNO INT PRIMARY KEY,
    DEPTNAME VARCHAR(150) UNIQUE,
    LOCATION VARCHAR(100)
);
CREATE TABLE PROJECT(
PROJECTNO INT PRIMARY KEY,
    PROJECTNAME VARCHAR(150) UNIQUE,
    LOCATION VARCHAR(100),
    DEPTNO INT,
    CONSTRAINT FOREIGN KEY(DEPTNO) REFERENCES DEPARTMENT(DEPTNO)
);
CREATE TABLE EMPLOYEE(
EMPNO INT PRIMARY KEY,
    EMPNAME VARCHAR(120) UNIQUE,
    ADDRESS VARCHAR(200),
    SALARY DOUBLE ,
    HIRINGDATE DATE,
    BIRTHDATE DATE,
    DEPTNO INT,
    CONSTRAINT FOREIGN KEY(DEPTNO) REFERENCES DEPARTMENT(DEPTNO)
);

CREATE TABLE EMPLOYEE_PHONES(
EMPNO INT,
    PHONES VARCHAR(50),
    CONSTRAINT FOREIGN KEY(EMPNO) REFERENCES DEPARTMENT(DEPTNO)
);
CREATE TABLE WORKON(
EMPNO INT,
    PROJECTNO INT,
    PRIMARY KEY(EMPNO,PROJECTNO),
    CONSTRAINT FOREIGN KEY(EMPNO) REFERENCES EMPLOYEE(EMPNO),FOREIGN KEY(PROJECTNO) REFERENCES PROJECT(PROJECTNO)
);

