CREATE VIEW PROJECT_DATA
AS
SELECT PROJECTNO AS 'PROJECT_NO',
PROJECTNAME AS 'PROJECT_NAME',
project.LOCATION,
PROJECT.DEPTNO AS 'DEPARTMENT_NO',
DEPTNAME AS 'DEPARTMENT'
FROM project,department
WHERE project.DEPTNO=department.DEPTNO