CREATE VIEW EMPLOYEE_DATA
AS 
SELECT EMPNO AS 'NUMBER',
EMPNAME AS 'NAME',
ADDRESS,SALARY,
HIRINGDATE AS 'HIRING_DATE',
BIRTHDATE AS 'DATE_OF_BIRH',
employee.DEPTNO AS 'DEPARTMENT_NO',
DEPTNAME AS 'DEPARTMENT'
FROM employee,department
WHERE EMPLOYEE.DEPTNO=department.DEPTNO
