CREATE VIEW EMPLOYEE_DATA
AS
SELECT EMPNO AS 'NUMBER',
	EMPNAME AS 'NAME',
	ADDRESS,
	SALARY,
	HIRINGDATE AS 'HIRING_DATE',
	BIRTHDATE AS 'DATE_OF_BIRTH',
	EMPLOYEE.DEPTNO AS 'DEPARTMENT_NO',
	DEPTNAME AS 'DEPARTMENT'
FROM EMPLOYEE , DEPARTMENT
WHERE EMPLOYEE.DEPTNO = DEPARTMENT.DEPTNO;




CREATE VIEW DEPARTMENT_DATA
AS
SELECT DEPTNO AS 'DEPARTMENT_NO',
	DEPTNAME AS 'DEPARTMENT',
	LOCATION
FROM DEPARTMENT	;




CREATE VIEW PROJECT_DATA
AS
SELECT PROJECTNO AS 'PROJECT_NO',
	PROJECTNAME AS 'PROJECT_NAME',
	PROJECT.LOCATION,
	PROJECT.DEPTNO AS 'DEPARTMENT_NO',
	DEPTNAME AS 'DEPARTMENT'
FROM PROJECT,DEPARTMENT
WHERE PROJECT.DEPTNO=DEPARTMENT.DEPTNO;

	
CREATE VIEW EMPLOYEE_PHONES_DATA
AS
SELECT EMPLOYEE.EMPNO AS 'EMPLOYEE_NO',
		EMPNAME AS 'EMPLOYEE_NAME',
		PHONE
FROM EMPLOYEE,EMPLOYEE_PHONES
WHERE EMPLOYEE.EMPNO=EMPLOYEE_PHONES.EMPNO;



CREATE VIEW WORKON_DATA
AS
SELECT WORKON.EMPNO AS 'EMPLOYEE_NO',
	EMPNAME AS 'EMPLOYEE_NAME',
	WORKON.PROJECTNO AS 'PROJECT_NO',
	PROJECTNAME AS 'PROJECT_NAME'
FROM WORKON,EMPLOYEE,PROJECT
WHERE
WORKON.EMPNO=EMPLOYEE.EMPNO
AND
WORKON.PROJECTNO=PROJECT.PROJECTNO;
	

		




	